
elasticsearch:
  cluster-name: docker-cluster
  host: 127.0.0.1
  port: 9200

---

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/post?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: local

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: test